# action.yml

name: 'Jupyter Notebooks to Markdown'
description: 'Convert Jupyter Notebooks within the repository to Markdown files'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book-open'  
  color: 'blue'
